%% Id Vs Vgs Characteristics
clc;clear all;
% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
Vd=1.8;
Vs=0;
W=1.8e-6;
L=0.36E-6;
Vg=-1:0.01:3.8;
for Vb=-0.5:0.25:0.5
[Ids,Vth] = N_18_MM_V2_C(Vd,Vg,Vs,Vb,W,L); %% this is the function as per BSIM model of MOS
% Ids=testIds(L,Vb,Vd,Vg,Vs,W);%% this is the function generated by symbolic toolbox 
Ids_micro=Ids/1e-6;
Leg=sprintf('Vbs= %s',num2str(Vb));
plot(Vg,Ids_micro,'Parent',axes1,'Color',[rand() rand() rand()],'LineWidth',1.5,'DisplayName',Leg);
grid on;
hold on;
xlabel('Vgs');
ylabel('Ids(\muA)');
title('Ids Vs Vgs for different Vbs for NMOS');
end
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.181684981684982 0.664296998420225 0.117582417582418 0.232227488151659]);
%% Id Vs Vds Characteristics
%% 
% Create figure
figure2 = figure;

% Create axes
axes2 = axes('Parent',figure2);
Vs=0;
Vb=0.4;
Vg=0.55;
L=1E-6;
Vd=0:0.01:1.8;
for W=0.18E-6:0.36E-6:1.8E-6;
% [Ids,Vth] = N_18_MM_V2_C(Vd,Vg,Vs,Vb,W,L); %% this is the function as per BSIM model of MOS 
Ids=testIds(L,Vb,Vd,Vg,Vs,W);%% this is the function generated by symbolic toolbox 
Ids_micro=Ids/1e-6;
Leg=sprintf('W=%sum',num2str(W/1e-6));
plot(Vd,Ids_micro,'Parent',axes2,'Color',[rand() rand() rand()],'LineWidth',1.5,'DisplayName',Leg);
grid on;
hold on;
xlabel('Vds');
ylabel('Ids (\muA)');
title('Ids Vs Vds for different Widths for NMOS');
end
legend2 = legend(axes2,'show');
set(legend2,...
    'Position',[0.721684981684982 0.134296998420225 0.117582417582418 0.232227488151659]);

% %% all the small signal parameters
% gm=del_Id./del_Vgs;
% gmb=del_Id./del_Vbs;
% gds=del_Id./del_Vds;
% ro=1./gds;
% gm_by_id=gm./Ids(1:length(Ids)-1);
% 
% figure4 = figure;
% axes4 = axes('Parent',figure4);
% grid on;
% hold on;
% % plot(Vgs(1:length(Vgs)-1),gm,'Color','r','LineWidth',1.5,'DisplayName','gm');
% % plot(Vgs(1:length(Vgs)-1),gmb,'Color','m','LineWidth',1.5,'DisplayName','gmb');
% % plot(Vgs(1:length(Vgs)-1),gds,'Color','b','LineWidth',1.5,'DisplayName','gds');
% plot(Vgs(1:length(Vgs)-1),gm_by_id,'Color','g','LineWidth',1.5,'DisplayName','gm/id');
% xlabel('Vgs');
% ylabel('Cij/COX');
% title('small signal parameters for NMOS');
% hold off;
% legend4 = legend(axes4,'show');
% set(legend4,...
%     'Position',[0.761684981684982 0.164296998420225 0.117582417582418 0.232227488151659]);